### ISSUE TITLE
Select menu does not show the selected option

### ISSUE THREAD

**Issue by Dinika** [inveniosoftware/invenio-search-js#109]
When using the `invenio-search-select-box` directive the option that the user chooses in the 'Sort by' menu is not displayed in the select box as shown below
![screenshot from 2017-12-22 17-18-41](https://user-images.githubusercontent.com/11242410/34305089-f12cea9e-e73c-11e7-80b1-de38439fa61d.png)

I believe this is because while [we are setting](https://github.com/inveniosoftware/invenio-search-js/blob/master/src/invenio-search-js/templates/selectBox.html#L3) the `value` attribute in the option tag as `option.value`, the option.value is getting modified from, say, `-bestmatch` to `bestmatch` (the dash is being removed) [here](https://github.com/inveniosoftware/invenio-search-js/blob/master/src/invenio-search-js/directives/invenioSearchSelectBox.js#L97).

I don't quite understand why the dash is being removed. When I tried running the code without removing the dash, it was running as expected and the selected option was getting rendered in the select box.

**Comment by lnielsen** [comment]
Ping @drjova

**Comment by drjova** [comment]
@lnielsen already working on it :)

**Comment by lnielsen** [comment]
Was this fixed? If not I'll include it in the upcoming Invenio sprint

**Comment by drjova** [comment]
actually it was a wrong sort configuration on our side

**Comment by slint** [comment]
@lnielsen @drjova Should this be closed? I guess the if there's anything to be done is to put some extra checking or default parameters so we could possibly add to prevent this from happening...

**Comment by drjova** [comment]
@slint this problem is connected with ``RECORDS_REST_SORT_OPTIONS ``. The way we sort things it's confusing because we have the sort option and the order option which are changing the same parameter.

Ideally we should have only the sort option which will include the order options. Like the following:

```
| Sort Options  ^ |
===================
| By Name (asc)   |
| --------------- |
| By Name (desc)  |
| --------------- |
| Older           |
| --------------- |
| Newer           |
```

IMO it doesn't worth to do any changes now since Invenio will change the UI framework soon.
