### ISSUE TITLE
search: search issues

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-search-js#24]
- [x] URL highjacking problem.
- [x] Facet title decorator example.
- [x] Pagination: do show end pages.
- [x] Sort by
- [x] Facets: allow select multiple facets
- [x] Simple example of how to plug custom template filters from overlay (e.g. strip html)
- [x] Page doesn't update from url

**Comment by drjova** [comment]
For `URL highjacking problem.`

We are using `html5mode` to enable the pretty urls `/search?q=iron+man` instead of `search/#?q=iron+man`. The issue can be solved either by adding `target="_self"` attribute to the template links or specify a `base` under which the `html5mode` will be active. The latter might be tricky for different installations.

**Comment by lnielsen** [comment]
:+1: Works :-)

**Comment by drjova** [comment]
For `Pagination: do show end pages.`

The pagination now is shown in the simplify version 

```
1 2 3 4 5 6 7 8 9
```
instead of 

```
1 2 3 4 5 6 7 8 9 .. 24 25
```
https://github.com/inveniosoftware/invenio-search-js/pull/25

**Comment by drjova** [comment]
Using filters in the overlay:

creating the filter
```javascript

define(['angular'], function(angular){
  var app = angular.module('myModule', [])
    .filter('upperCase', upperCaseFilter);
  function upperCaseFilter() {
    return function(input, ellipsis) {
      var out = input.toUpperCase()
      if (ellipsis) {
        out = out + '...';
      }
      return out;
    }
  }
  // Return the module
  return app;
});
```
Add `myModule` app 

```javascript

require([
    'angular'
    'js/myModule.js'
  ], function(angular, myModule) { 
    angular.element(document).ready(function() {
      angular.bootstrap(document, ['myModule']);
    });
});
```

Then anywhere something like

```jinja
<!-- JARVIS -->
{{ "Jarvis" | upperCase }}
```

```html
<!-- JARVIS... -->
{{ "Jarvis" | upperCase:true }}
```


A slightly more complex, elegant, requirejs friendly and **working** example: https://github.com/drjova/cds-demosite/commit/9eaf35215cccd69e4774be60a26e96f1966010d9
