### ISSUE TITLE
customizable $http content-type

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio-search-js#53]
As our records contain a lot of information due to big author lists and reference lists, a search can download more than 2Mb which slows it down.

We need to trim down the JSON returned to the client for brief search results so one solution is to offer a serializer with a custom content type, say `Content-type: application/vnd+inspire.brief+json` that will do some processing and return to the client.

```
RECORDS_REST_ENDPOINTS = dict(
    literature=dict(
        pid_type='literature',
        pid_minter='inspire_recid_minter',
        pid_fetcher='inspire_recid_fetcher',
        search_index='records-hep',
        search_type='hep',
        record_serializers={
            'application/json': ('invenio_records_rest.serializers'
                                 ':json_v1_response'),
        },
        search_serializers={
            'application/json': ('invenio_records_rest.serializers'
                                 ':json_v1_search'),
            'application/vnd+inspire.brief+json': ('inspirehep.serializers'
                                 ':json_brief_search'),

        },
        list_route='/literature/',
        item_route='/literature/<pid_value>',
        default_media_type='application/json',
        max_result_window=10000,
        query_factory_imp='inspirehep.modules.search.query:inspire_query_factory',
    ),
```

At the moment, only `params` can be customized (https://github.com/inveniosoftware/invenio-search-js/blob/master/src/invenio-search-js/invenioSearch.module.js#L1309) when calling `$http` so the headers cannot be altered to use this custom content type.

@lnielsen @drjova do you think this is a good solution? And in that case, can it be added to `invenio-search-js` ?

**Comment by drjova** [comment]
@jmartinm yep that's true we can add customisable headers but there is another more app specific solution with [decorators](https://docs.angularjs.org/api/auto/service/$provide#provider) a quick example:


```
 $provide.decorator(‘invenioSearchAPI', function($delegate) {
     // Save the default function
     var searchFn = $delegate.search;
     $delegate.search = function(args) {
       /*
        * Args Object look like:
        *
        *   {
        *      url: ....
        *      method: ....
        *      params: ....
        *   }
        *
        */
       args["headers"] = {
         'Content-Type': 'application/vnd+inspire.brief+json'
       }
       // Call the original function with the enchanced parameters
       searchFn(args);
    };
    return $delegate; 
});
```

**Comment by lnielsen** [comment]
I do think it makes sense that you can modify the content type. I.e. something a long the lines of:

```
<invenio-search 
 search-endpoint="http://localhost:5000/api/records/" 
 content-type="application/json">
```

@jmartinm Will you make a PR? In our end we don't have time to do right now as we're sprinting on other stuff. If you also don't have time, then I suggest that you for now just change the ``application/json`` serialiser to deliver the brief JSON (which might not be a bad idea anyway). Later you can use the ``application/vnd.inspire.full+json`` content type to deliver full records in the search view.

**Comment by jmartinm** [comment]
The solution mentioned by @drjova works so there is no immediate need for it. If we want to make it part of the `invenio-search` directive, let's leave this open and either me or @drjova can take care of it.

**Comment by jmartinm** [comment]
This was already done.
