### ISSUE TITLE
facets: on access via direct link, facet cannot be deselected

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-search-js#67]
e.g. go to https://qa.inspirehep.net/search?page=1&size=25&doc_type=preprint

Then try to deselect the facet. I believe this is related to #66.

cc @jmartinm

**Comment by lnielsen** [comment]
I've seen similar on zenodo. Is it something you perhaps could take a look at?

**Comment by eamonnmag** [comment]
I'll have a check. I think I have an idea of its source. I'm writing another angular app for the holding pen now. Need to progress on that first, then I'll check on this ASAP.
