### ISSUE TITLE
Facets order

### ISSUE THREAD

**Issue by jma** [inveniosoftware/invenio-search-js#89]
As I understood it not possible to have a fixed order for facets. It would be nice to have it.

**Comment by drjova** [comment]
@jma thanks! Indeed right now it gets the order from ElasticSearch

**Comment by jma** [comment]
Yes, but it would be great to give the wanted order in the config file.

**Comment by jma** [comment]
After some discussion with @lnielsen , it should be done in the `invenio-records-rest`.

**Comment by drjova** [comment]
Moved to https://github.com/inveniosoftware/invenio-records-rest/issues/141

**Comment by lnielsen** [comment]
Isn't this issue still needed? I mean if we e.g. add an order attribute in the output then angular needs to be able to order the results?

**Comment by drjova** [comment]
If we add a new attribute then yes 👍 (I didn't know about the discussed solution), I'm reopening the issue.
