### ISSUE TITLE
templates: pagination with numbers

### ISSUE THREAD

**Issue by drjova** [inveniosoftware/invenio-search-js#9]
Add pagination with numbers instead from ``Next`` and ``Previous`` buttons

example

```text
<< < [1 2 3 ... 10 11 12] > >>
```

**Comment by drjova** [comment]
does this pagination cover all basic cases? cc @tiborsimko @jirikuncar @lnielsen 

![screen shot 2015-12-04 at 18 44 12](https://cloud.githubusercontent.com/assets/4287772/11596713/12cc419c-9ab7-11e5-8cec-30fd081afc23.png)

**Comment by lnielsen** [comment]
LGTM

**Comment by jirikuncar** [comment]
:+1:
